network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      optional: true
      gateway4: 192.168.1.1 # NOTE: you must change this to match your local Router/LAN
      nameservers:
        addresses:
          - "192.168.1.1"
          - "1.1.1.1"
          - "8.8.8.8"
      addresses:
        - "192.168.1.202/24"
