---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-nvme
  namespace: default
spec:
  storageClassName: rook-block-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
