---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-hdd
  namespace: default
spec:
  storageClassName: rook-block-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
