---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: hdd
  namespace: rook-ceph
spec:
  deviceClass: hdd
  # NOTE: with enough hosts, use a failureDomain of host for greater durability
  failureDomain: osd
  # NOTE: since there are only 2 of each kind of drive, we can only replicate 2 assuming 1 OSD per drive 
  replicated:
    size: 2
