namespace: rook-ceph

generatorOptions:
  disableNameSuffixHash: false

resources:
  # Rook Requirements
  - crds.yaml
  - common.yaml
  - operator.yaml

  # Cluster
  - rook-ceph.cluster.yaml

  # Blockpools
  - nvme.cephblockpool.yaml
  - ssd.cephblockpool.yaml
  - hdd.cephblockpool.yaml
  - hybrid-nvme-ssd.cephblockpool.yaml
  - hybrid-nvme-hdd.cephblockpool.yaml
  - hybrid-ssd-hdd.cephblockpool.yaml

  # Storage classes
  - rook-block-nvme.storageclass.yaml
  - rook-block-ssd.storageclass.yaml
  - rook-block-hdd.storageclass.yaml
  - rook-block-hybrid-nvme-ssd.storageclass.yaml
  - rook-block-hybrid-nvme-hdd.storageclass.yaml
  - rook-block-hybrid-ssd-hdd.storageclass.yaml

  # PG
  - pg.configmap.yaml
  - pg.pvc.yaml
  - postgres.deployment.yaml
  - postgres.svc.yaml
  - pgbench.job.yaml
