---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg
  namespace: default
spec:
  storageClassName: rook-block-hdd # rook-block-ssd | rook-block-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
